input.onButtonPressed(Button.A, function () {
    music.ringTone(262)
    music.ringTone(262)
    music.ringTone(392)
    music.ringTone(392)
    music.ringTone(440)
    music.ringTone(440)
    music.play(music.tonePlayable(392, music.beat(BeatFraction.Double)), music.PlaybackMode.UntilDone)
    music.ringTone(349)
    music.ringTone(349)
    music.ringTone(330)
    music.ringTone(330)
    music.ringTone(294)
    music.ringTone(294)
    music.play(music.tonePlayable(262, music.beat(BeatFraction.Double)), music.PlaybackMode.UntilDone)
    music.ringTone(392)
    music.ringTone(392)
    music.ringTone(349)
    music.ringTone(349)
    music.ringTone(330)
    music.ringTone(330)
    music.play(music.tonePlayable(294, music.beat(BeatFraction.Double)), music.PlaybackMode.UntilDone)
    music.ringTone(392)
    music.ringTone(392)
    music.ringTone(349)
    music.ringTone(349)
    music.ringTone(330)
    music.ringTone(330)
    music.play(music.tonePlayable(294, music.beat(BeatFraction.Double)), music.PlaybackMode.UntilDone)
    music.ringTone(262)
    music.ringTone(262)
    music.ringTone(392)
    music.ringTone(392)
    music.ringTone(440)
    music.ringTone(440)
    music.play(music.tonePlayable(392, music.beat(BeatFraction.Double)), music.PlaybackMode.UntilDone)
    music.ringTone(349)
    music.ringTone(349)
    music.ringTone(330)
    music.ringTone(330)
    music.ringTone(294)
    music.ringTone(294)
    music.play(music.tonePlayable(262, music.beat(BeatFraction.Double)), music.PlaybackMode.UntilDone)
})
input.onButtonPressed(Button.B, function () {
    music._playDefaultBackground(music.builtInPlayableMelody(Melodies.Ode), music.PlaybackMode.InBackground)
})
music.setVolume(255)
basic.forever(function () {
	
})
